version: '3.9'

services:
  mongodb:
    image: mongo:8.0.0-rc16-jammy
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - networkflask

  flaskapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskapi
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    restart: always
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - networkflask
    env_file:
      - .env

networks:
  networkflask:
    driver: bridge
